#!/usr/bin/env bash
set -ex
echo "ENVIRONMENT $BRANCH"
export REPO_NAME="devops-challenge-function"
FUNCTION_NAME="NONE"
if [ "$BRANCH" = "sandbox" ]; then
    echo "HERE"
    echo "Function name ${FUNCTION_NAME}"
    FUNCTION_NAME="$REPO_NAME-sandbox"
fi
if [ "$BRANCH" = "staging" ]; then
  FUNCTION_NAME="$REPO_NAME-staging"
fi
if [ "$BRANCH" = "main" ]; then
  FUNCTION_NAME="$REPO_NAME-prod"
fi

if [ "$FUNCTION_NAME" = "NONE" ]; then
  echo 'Error: lambda function name is not defined'
  exit 1
fi

cd ./functions/resizePhoto/src
ls -lah
aws s3 cp ${REPO_NAME}.zip s3://devops-challenge-lci/$BRANCH/

# aws lambda update-function-code \
#   --function-name "$FUNCTION_NAME" \
#   --region us-east-2 \
#   --s3-bucket devops-challenge-lci \
#   --s3-key "$BRANCH/${REPO_NAME}.zip"

echo "Deployed $FUNCTION_NAME from $BRANCH!"