version: '3.9'

services:
  admin:
    build:
      context: ./
      dockerfile: packages/admin/dockerfile
    restart: always
    ports:
      - 9000:3001

  database:
    build:
      context: ./
      dockerfile: packages/database/dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: my_postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: